# Numpy Notes

* **What is Numpy?**
    * **Python library for creating N-dimensional arrays**
    * **Ability to quickly broadcast functions**
    * **Built-in linear algebra,statistical distributions,trigonometric and random number capabilities**
      

## How to create numpy array from existing array

In [32]:
## First We import numpy as--
import numpy as np

## Here is our actual List
list = [1,2,3,4,5,6,7,8]
list

[1, 2, 3, 4, 5, 6, 7, 8]

In [17]:
type(list)

list

In [15]:
## Here is how we create a numpy array
## When we use this, it returns a numpy array, it doesnt change the actural one
np.array(list)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [18]:
## Here type of actural list does not change 
type(list)

list

In [19]:
## To change the actural list, We do this
list = np.array(list)

## Now lets see the type
type(list)

## Its numpy array 

numpy.ndarray

In [20]:
## We can use numpy array with nested arrays as well and it will represent itself in more readble way
new_list = [[1,2,3],[4,5,6],[7,8,9]]
np.array(new_list)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
## This is what happens when we try to create array other than m x n representation
## It will give us an error
new_list = [[1,],[4,5,6],[7,8]]
np.array(new_list)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

## Creating instant numpy arrays with built-in functions

In [24]:
## To create a numpy array with only zeros , we use this
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [29]:
## If we want to create 2d-matrix,we can use like this--

np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [30]:
## By default it use float data type,We can change it as
np.zeros(5,dtype='int')

array([0, 0, 0, 0, 0])

In [44]:
## Similarly, We can create a arrays of one
## And same arguments passed as zeros method
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [48]:
## We aslo have method for creating identity matrix
## If we pass only one arguemnt then it will create square matrix of that
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [49]:
## If we pass two argument then we create N-dimensional identity matrix
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

### Methods to create numpy array in range

In [35]:
## It create numpy array in range
np.arange(4,10)

array([4, 5, 6, 7, 8, 9])

In [36]:
## We can also pass third argument in arange method
## It is taken as 'step' (It create value on an interval of given step)
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [40]:
## We have a similar function just like arange which is linspace
## First two arguments are range with last one included
## Third one is how many no u want in the given range on equal interval
np.linspace(1,10,4)

array([ 1.,  4.,  7., 10.])

### Methods to create numpy array with random values

In [50]:
## When we dont pass any arguement then it will give us one random value between 0 and 1
np.random.rand()

0.7394315977553527

In [53]:
## It takes two arguments as rows and columns
np.random.rand(2,3)

array([[0.75221036, 0.50863999, 0.04274735],
       [0.58576151, 0.54396489, 0.30322172]])

In [55]:
## We can create random values in range as
## First two argument is range
## Third is size passed as (rows,columns)
np.random.randint(10,20,5)

array([16, 16, 15, 11, 16])

In [56]:
np.random.randint(10,20,(4,5))

array([[18, 13, 17, 14, 10],
       [18, 14, 15, 13, 17],
       [17, 11, 12, 17, 13],
       [12, 16, 17, 11, 15]])