# Numpy Notes

* **What is Numpy?**
    * **Python library for creating N-dimensional arrays**
    * **Ability to quickly broadcast functions**
    * **Built-in linear algebra,statistical distributions,trigonometric and random number capabilities**
      

## How to create numpy array from existing array

In [3]:
## First We import numpy as--
import numpy as np

## Here is our actual List
list = [1,2,3,4,5,6,7,8]
list

[1, 2, 3, 4, 5, 6, 7, 8]

In [17]:
type(list)

list

In [15]:
## Here is how we create a numpy array
## When we use this, it returns a numpy array, it doesnt change the actural one
np.array(list)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [18]:
## Here type of actural list does not change 
type(list)

list

In [19]:
## To change the actural list, We do this
list = np.array(list)

## Now lets see the type
type(list)

## Its numpy array 

numpy.ndarray

In [20]:
## We can use numpy array with nested arrays as well and it will represent itself in more readble way
new_list = [[1,2,3],[4,5,6],[7,8,9]]
np.array(new_list)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
## This is what happens when we try to create array other than m x n representation
## It will give us an error
new_list = [[1,],[4,5,6],[7,8]]
np.array(new_list)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

## Creating instant numpy arrays with built-in functions

In [24]:
## To create a numpy array with only zeros , we use this
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [29]:
## If we want to create 2d-matrix,we can use like this--

np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [30]:
## By default it use float data type,We can change it as
np.zeros(5,dtype='int')

array([0, 0, 0, 0, 0])

In [44]:
## Similarly, We can create a arrays of one
## And same arguments passed as zeros method
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [48]:
## We aslo have method for creating identity matrix
## If we pass only one arguemnt then it will create square matrix of that
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [49]:
## If we pass two argument then we create N-dimensional identity matrix
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

### Methods to create numpy array in range

In [35]:
## It create numpy array in range
np.arange(4,10)

array([4, 5, 6, 7, 8, 9])

In [36]:
## We can also pass third argument in arange method
## It is taken as 'step' (It create value on an interval of given step)
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [40]:
## We have a similar function just like arange which is linspace
## First two arguments are range with last one included
## Third one is how many no u want in the given range on equal interval
np.linspace(1,10,4)

array([ 1.,  4.,  7., 10.])

### Methods to create numpy array with random values

In [50]:
## When we dont pass any arguement then it will give us one random value between 0 and 1
np.random.rand()

0.7394315977553527

In [53]:
## It takes two arguments as rows and columns
np.random.rand(2,3)

array([[0.75221036, 0.50863999, 0.04274735],
       [0.58576151, 0.54396489, 0.30322172]])

In [55]:
## We can create random values in range as
## First two argument is range
## Third is size passed as (rows,columns)
np.random.randint(10,20,5)

array([16, 16, 15, 11, 16])

In [5]:
np.random.randint(10,20,(4,5))

array([[15, 10, 17, 13, 12],
       [14, 17, 19, 16, 11],
       [11, 18, 17, 19, 15],
       [12, 18, 17, 15, 14]])

## Methods to use with Numpy arrays

In [24]:
## Creating an array to perfrom operations
new_array = np.random.randint(1,50,10)
new_array

array([48, 37, 35,  5, 32, 19, 27, 22, 21,  6])

In [27]:
## To get the maximum number
new_array.max()

48

In [28]:
## To get the index of max number
new_array.argmax()

0

In [29]:
## To get the minimum number
new_array.min()

5

In [30]:
## To get the index of min number
new_array.argmin()

3

In [31]:
## We can reshape any array into any form
new_array.reshape(5,2)

array([[48, 37],
       [35,  5],
       [32, 19],
       [27, 22],
       [21,  6]])

In [32]:
## In original array we had 15 elements
## If we try to reshape it into any form other than m x n = 15 , it will give use an error
new_array.reshape(2,4)

ValueError: cannot reshape array of size 10 into shape (2,4)

In [68]:
## We can check the data type inside numpy array
new_array.dtype

dtype('int32')

In [70]:
## We can check the shape of any array
new_array.shape

(9,)

## Indexing and Selection of Elements

In [50]:
new_array = np.arange(1,10)
new_array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
## To grab some element
## It work similar as in list
new_array[1]

## We can do the same with 2-d array

2

In [52]:
## We can slice through an slement as
new_array[1:4]

array([2, 3, 4])

In [53]:
## If we donot know what the ending is
new_array[1:]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
## If we dont know what the starting is
new_array[:5]

array([1, 2, 3, 4, 5])

In [55]:
## We can also asign some value to the sliced elements
new_array[1:4] = 101
new_array

## Here we can see that it changes the actual array itself

array([  1, 101, 101, 101,   5,   6,   7,   8,   9])

In [59]:
## If we do like this, then also it changes the actual array
new_array = np.arange(1,10)
slice_of_array = new_array[1:4]
slice_of_array[1:4] = 100

print(new_array)
print(slice_of_array)

[  1   2 100 100   5   6   7   8   9]
[  2 100 100]


In [61]:
## If we dont want to change in the actual array , copy  method is useful
new_array = np.arange(1,10)
other_array = new_array.copy()
other_array[:] = 99

print(other_array)
print(new_array)

[99 99 99 99 99 99 99 99 99]
[1 2 3 4 5 6 7 8 9]


#### How to slice through 2-d array

In [71]:
arr = np.arange(1,10)
arr_2d = arr.reshape(3,3)
print(arr_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [74]:
## To find any particular element
arr_2d[0,1]

2

In [67]:
## To slice through this
## First argument represent  row slicing and second argument represent column slicing
arr_2d[0:2, 1: ]

array([[2, 3],
       [5, 6]])

#### How to filter in an array

In [76]:
new_array = np.arange(0,10)

new_array < 5
## It returns boolean array which follows the condition

array([ True,  True,  True,  True,  True, False, False, False, False,
       False])

In [77]:
## We can do this directly as--
new_array[new_array < 5]

array([0, 1, 2, 3, 4])

#### Arithmatic Operations to perform on array

In [82]:
new_array = np.arange(0,10)
print(new_array)

new_array + 5

[0 1 2 3 4 5 6 7 8 9]


array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [83]:
new_array - 5

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4])

In [84]:
new_array * 5

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [91]:
new_array / 5

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8])

In [93]:
new_array / 0
## With list ,it would have give us an error with no output if we would have divide it by 0
## Here it is giving us warning but also giving us an output

C:\Users\avi88\AppData\Local\Temp\ipykernel_16640\614795089.py:1: RuntimeWarning: divide by zero encountered in divide
  new_array / 0
C:\Users\avi88\AppData\Local\Temp\ipykernel_16640\614795089.py:1: RuntimeWarning: invalid value encountered in divide
  new_array / 0


array([nan, inf, inf, inf, inf, inf, inf, inf, inf, inf])

In [94]:
## inf means infinity
## nan - not a number
1 / new_array

C:\Users\avi88\AppData\Local\Temp\ipykernel_16640\253149594.py:1: RuntimeWarning: divide by zero encountered in divide
  1 / new_array


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [86]:
## We can perform these arithmatic operation with other arrays also
new_array + new_array

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [90]:
other_array = np.arange(2,8)
print(other_array)
new_array + other_array

## if we try to perform arithmatic operations on arrays with different shape then it will give us an error

[2 3 4 5 6 7]


ValueError: operands could not be broadcast together with shapes (10,) (6,) 

### Prebuilt methods to perform arithmatic operations on numpy array

In [101]:
## To get sum of every element
new_array.sum()

45

In [97]:
## To get mean of every element
new_array.mean()

4.5

In [98]:
## To get variance of every element
new_array.var()

8.25

In [99]:
new_array.max()
new_array.min()

0

In [100]:
## To get standard deviation of every element
new_array.std()

2.8722813232690143

In [4]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
## To perform operations across rows and columns in 2d array
## We can pass axis as first argument in all these methods

## axis = 1 means it will give array of sum across rows
arr_2d.sum(axis=1)

array([ 6, 15, 24])

In [7]:
## axis = 0 means it will give array of sum across colums
arr_2d.sum(axis=0)

array([12, 15, 18])

### Other built in numpy method to easily calculate mathematical operations

In [9]:
new_array = np.arange(1,10)
new_array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
## To calculate square root of every element
np.sqrt(new_array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        ])

In [13]:
## To calculate sin of every element
np.sin(new_array)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [14]:
## To calculate log
np.log(new_array)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458])